<a href="https://colab.research.google.com/github/danthonyrodriguez/Colab-Notebooks/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
from google.colab import drive
drive.mount('/content/drive')

file = "/content/drive/MyDrive/Civilian Cyber Warrior Project/merge_wc_edit_update.csv"
df = pd.read_csv(file)
df.info()

Mounted at /content/drive
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1099 entries, 0 to 1098
Columns: 206 entries, NO to Q34_Max
dtypes: float64(106), int64(54), object(46)
memory usage: 1.7+ MB

In [6]:
#PCA for Emotive National Identity
PCA1 = df[["Q36_2", "Q36_3", "Q36_4", "Q36_5", "Q36_7", "Q36_8"]]
PCA1 = PCA1.fillna(0)
PCA1 = np.array(PCA1)
x=PCA1
x=StandardScaler().fit_transform(x)
pca = PCA(n_components = 1)
principalComponent1 = pca.fit_transform(x)
df['Principal_Component1'] = principalComponent1
print(pca.explained_variance_ratio_)

[0.62174734]

In [7]:
#PCA for Belief in Group Equality
PCA2 = df[["Q37_4", "Q37_5", "Q37_6", "Q37_7", "Q37_8", "Q37_9", "Q37_10"]]
PCA2 = PCA2.fillna(0)
PCA2 = np.array(PCA2)
x=PCA2
x=StandardScaler().fit_transform(x)
pca = PCA(n_components = 1)
principalComponent2 = pca.fit_transform(x)
df['Principal_Component2'] = principalComponent2
print(pca.explained_variance_ratio_)

[0.48780837]

In [8]:
#PCA for Outgroup Antagonism
PCA3 = df[["Q36_17", "Q36_21", "Q37_1", "Q37_2", "Q37_3"]]
PCA3 = PCA3.fillna(0)
PCA3 = np.array(PCA3)
x=PCA3
x=StandardScaler().fit_transform(x)
pca = PCA(n_components = 1)
principalComponent3 = pca.fit_transform(x)
df['Principal_Component3'] = principalComponent3
print(pca.explained_variance_ratio_)

[0.64945379]

In [5]:
df.head()

     NO  DataFileCountryofOrigin  ...  Principal_Component2 Principal_Component3
0   sg1                        2  ...              1.851208            -0.300583
1  en38                        2  ...             10.208954             3.418556
2  re25                        2  ...              0.803086            -1.538089
3  re47                        2  ...             -1.926144            -0.177975
4  re44                        2  ...              3.268752            -1.991428

[5 rows x 209 columns]

The last item on the email from Dr. Kilger is #8:
check the variables from "additional variables" slide and make sure that they look ready for analysis


*   Measure of technical expertise with computers (column "TechnologicalSkill"?)
*   Measure of past experience with piracy of         additional software and media (Column "Piracy"?)
*   Gender
*   Age
*   Country

In [ ]:
otherVariables = df[["Age", "Q44", "Gender", "DataFileCountryofOrigin", "TechnologicalSkill", "Piracy"]]
otherVariables.dtypes

Age                        float64
Q44                         object
Gender                     float64
DataFileCountryofOrigin      int64
TechnologicalSkill          object
Piracy                      object
dtype: object

In [10]:
df['TechnologicalSkill'].head()

0    22
1    34
2    20
3    27
4    20
Name: TechnologicalSkill, dtype: object